name: Run Selenium Pytest with Allure

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      # 4️⃣ Set up Chrome and ChromeDriver
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      # 5️⃣ Install ChromeDriver (matching Chrome version)
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # 6️⃣ Verify Chrome and ChromeDriver
      - name: Verify installations
        run: |
          google-chrome --version
          chromedriver --version

      # 7️⃣ Run tests with Allure results
      - name: Run tests with Allure results
        run: |
          pytest --alluredir=allure-results
        continue-on-error: true

      # 8️⃣ Set up Java (required for Allure)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 9️⃣ Install Allure CLI
      - name: Install Allure commandline
        run: npm install -g allure-commandline

      # 🔟 Generate HTML Allure report
      - name: Generate Allure report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      # 1️⃣1️⃣ Upload the report as an artifact
      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      # 1️⃣2️⃣ Deploy Allure HTML report to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        if: github.ref == 'refs/heads/main' && always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report