name: Selenium CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager pytest-html

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Check Chrome version
        run: google-chrome --version

      - name: Run tests
        env:
          GITHUB_ACTIONS: true
        run: |
          mkdir -p reports
          pytest \
            --html=reports/test_report.html \
            --self-contained-html \
            --junitxml=reports/junit.xml \
            -v \
            --tb=short
        continue-on-error: false
      

      - name: Upload pytest HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/test_report.html

      - name: Upload JUnit XML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-xml-report
          path: reports/junit.xml

      - name: Pytest Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: reports/junit.xml