name: Run Selenium Pytest with Allure

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install selenium pytest-xdist allure-pytest webdriver-manager

      # 4️⃣ Run tests with Allure results (headless via env variable)
      - name: Run tests with Allure results
        env:
          HEADLESS: "true"     # ✅ Your conftest uses Config.HEADLESS to enable headless
        run: |
          pytest --alluredir=allure-results -n auto

      # 5️⃣ Install Allure commandline
      - name: Install Allure commandline
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre
          npm install -g allure-commandline --save-dev

      # 6️⃣ Generate Allure report
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      # 7️⃣ Upload Allure report artifact
      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
