name: Run Selenium Pytest with Allure

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install selenium pytest-xdist allure-pytest webdriver-manager
      
      

      - name: Run tests with Allure results
        run: |
          pytest --alluredir=allure-results -n auto 

      - name: Install Allure commandline
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre
          npm install -g allure-commandline --save-dev

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
